name: Make Builds

on:
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}

jobs:
  buildTargetPlatforms:
    name: Build for ${{ matrix.targetPlatform.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - name: windows
            platform: StandaloneWindows64
          #- name: linux
          #  platform: StandaloneLinux64
          #- name: mac
          #  platform: StandaloneOSX
          - name: webgl
            platform: WebGL
    steps:

      #- name: Free Disk Space (Ubuntu)
      #  if: matrix.targetPlatform.platform == 'WebGL'
      #  uses: jlumbroso/free-disk-space@main
      #  with:
      #    tool-cache: false
      #    android: true
      #    dotnet: false
      #    haskell: false
      #    large-packages: false
      #    docker-images: false
      #    swap-storage: false
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-build-${{ matrix.targetPlatform.platform }}
          restore-keys: |
            Library-build-
            Library-

      - uses: game-ci/unity-builder@v4.3.0
        with:
          targetPlatform: ${{ matrix.targetPlatform.platform }}
          unityVersion: 6000.0.42f1
          buildName: Build

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform.name }}
          path: build/${{ matrix.targetPlatform.platform }}

      - name: Deploy to itch.io
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: ${{ matrix.targetPlatform.name }}
          # VERSION: 1.0
          ITCH_GAME: ld57
          ITCH_USER: cammin
          PACKAGE: build/${{ matrix.targetPlatform.platform }}
